Repository metallb/frr-k8s, pull requests merged in 2024-10, with the labels that each got.

#204 E2E: make Graceful Restart test more resilient when restarting pods takes time
  .github/workflows/composite/collectlogs/action.yaml
  e2etests/pkg/k8s/pods.go
  e2etests/tests/graceful_restart.go
Labels: kind/flake

#206 Remove the port from the peer metrics label
  e2etests/tests/metrics.go
  frr-tools/metrics/collector/bgp.go
  frr-tools/metrics/collector/bgp_test.go
Labels: kind/bug

#202 Makefile: bump the ginkgo version and add a dependency on kubectl
  Makefile
Labels: kind/cleanup

#211 Frr config: add route map detail in debug
  internal/frr/templates/frr.tmpl
Labels: kind/cleanup
