Repository metallb/frr-k8s, pull requests merged in 2025-03, with the labels that each got.

#265 Prefix lists: define before using them
  internal/frr/templates/filters.tmpl
  internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6.golden
  internal/frr/testdata/TestMultipleNeighborsOneV4AndOneV6DisableMP.golden
  internal/frr/testdata/TestMultipleRoutersImportVRFs.golden
  internal/frr/testdata/TestMultipleRoutersMultipleNeighs.golden
  internal/frr/testdata/TestSingleSession
  internal/frr/testdata/TestSingleSession.golden
  internal/frr/testdata/TestSingleSessionBFD.golden
  internal/frr/testdata/TestSingleSessionWithAlwaysBlock.golden
  internal/frr/testdata/TestSingleSessionWithEBGPMultihop.golden
  internal/frr/testdata/TestSingleSessionWithEBGPMultihopAndExtras.golden
  internal/frr/testdata/TestSingleSessionWithExternalASN.golden
  internal/frr/testdata/TestSingleSessionWithGracefulRestart.golden
  internal/frr/testdata/TestSingleSessionWithIPv6SingleHop.golden
  internal/frr/testdata/TestSingleSessionWithInternalASN.golden
  internal/frr/testdata/TestSingleUnnumberedSession.golden
  internal/frr/testdata/TestTwoRoutersTwoNeighbors.golden
  internal/frr/testdata/TestTwoRoutersTwoNeighborsBFD.golden
  internal/frr/testdata/TestTwoSessionsAcceptAll.golden
  internal/frr/testdata/TestTwoSessionsAcceptSomeV4.golden
  internal/frr/testdata/TestTwoSessionsAcceptV4AndV6.golden
Labels: kind/cleanup

#257 Add BGPSessionState
  API-DOCS.md
  Dockerfile
  Makefile
  api/v1beta1/bgp_session_state_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/frr-k8s/README.md
  charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_bgpsessionstates.yaml
  charts/frr-k8s/templates/controller.yaml
  charts/frr-k8s/templates/rbac.yaml
  charts/frr-k8s/values.yaml
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/crd/bases/frrk8s.metallb.io_bgpsessionstates.yaml
  config/crd/kustomization.yaml
  config/frr-k8s/frr-k8s.yaml
  config/rbac/role.yaml
  config/rbac/secrets_role.yaml
  e2etests/pkg/dump/k8s.go
  e2etests/tests/bgp_session_status.go
  frr-tools/metrics/collector/bfd.go
  frr-tools/metrics/collector/bgp.go
  frr-tools/metrics/vtysh/bfd.go
  frr-tools/metrics/vtysh/bgp.go
  frr-tools/status/controller/bgpsessionstate_controller.go
  frr-tools/status/controller/bgpsessionstate_controller_test.go
  frr-tools/status/controller/common_test.go
  frr-tools/status/exporter.go
  internal/frr/parse.go
  internal/frr/parse_test.go
Labels: kind/feature

#276 Add BGPSessionState docs
  README.md
  api/v1beta1/bgp_session_state_types.go
  charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_bgpsessionstates.yaml
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/crd/bases/frrk8s.metallb.io_bgpsessionstates.yaml
Labels: kind/documentation

#272 Set a limit on the number of open fds
  charts/frr-k8s/templates/controller.yaml
  config/all-in-one/frr-k8s-prometheus.yaml
  config/all-in-one/frr-k8s.yaml
  config/frr-k8s/frr-cm.yaml
Labels: kind/cleanup
